# -*- coding: utf-8 -*-
"""emotion1222-random.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qArfnjYO_STqNew2c2hzZDDOMxRzsrdi
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import random
import cv2
import numpy as np
from keras.preprocessing.image import img_to_array
from keras.models import load_model
import matplotlib.pyplot as plt

base_folder = '/content/drive/MyDrive/1222Project/dataset'

image_paths = []
for root, dirs, files in os.walk(base_folder):
    for file in files:
        if file.lower().endswith(('.jpg', '.jpeg', '.png')):
            image_paths.append(os.path.join(root, file))

if not image_paths:
    raise ValueError("資料夾中沒有找到任何圖片，請確認路徑與檔案格式是否正確")

random_path = random.choice(image_paths)
print(f"隨機選中圖片：{random_path}")

img = cv2.imread(random_path, cv2.IMREAD_GRAYSCALE)
img_resized = cv2.resize(img, (64, 64))
img_normalized = img_resized.astype("float") / 255.0
img_tensor = img_to_array(img_normalized)
img_tensor = np.expand_dims(img_tensor, axis=0)

!wget https://github.com/oarriaga/face_classification/raw/master/trained_models/emotion_models/fer2013_mini_XCEPTION.102-0.66.hdf5 -O model.h5

model = load_model('model.h5', compile=False)

emotion_labels = ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']

prediction = model.predict(img_tensor)[0]
predicted_label = emotion_labels[np.argmax(prediction)]
print(f"Predicted Emotion: {predicted_label}")
for label, prob in zip(emotion_labels, prediction):
    print(f"{label}: {prob:.4f}")

plt.imshow(img_resized, cmap='gray')
plt.title(f'Predicted: {predicted_label}')
plt.axis('off')
plt.show()